install.packages("ggplot2")
install.packages("circlize")
install.packages("grDevices")
install.packages("RSQLite")
install.packages("http://d3gb.usal.es/docs/package/r/D3GB_1.1.tar.gz", repos=NULL, type="source")
install.packages("glue")
install.packages("optparse")
